name: Generate swift package collection

on:
  schedule:
    - cron: "* 9 * * 1,4"
#   push:
#     branches: [ main ]

jobs:
  generate: 
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: clone package-collection-generate
      run: git clone https://github.com/cezres/swift-package-collection-generator.git
    - name: build package-collection-generate
      run: |
        cd ./swift-package-collection-generator
        swift build --configuration release
    - name: run package-collection-generate
      run: |
        cd ./swift-package-collection-generator
        ./.build/release/package-collection-generate ../packages.json ../collection.json 
    - name: push collection.json
      run: |
        git config user.name 晨风
        git config user.email cezres@163.com
        git add ./collection.json
        git commit -m "Update collection.json"
        git push
